# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
# Ans 1.1
import random
import numpy as np
num1 = np.random.randint(1,21,size=(5,5))
print(f"original array:\n{num1}")
num1[:,2] = 1
print(f"\nmodified array:\n{num1}")


original array:
[[ 3 19 13  4  6]
 [ 2  3 12 16 11]
 [ 2 20  6  8  1]
 [ 4 11 13 10  6]
 [16 16 19  7  6]]

modified array:
[[ 3 19  1  4  6]
 [ 2  3  1 16 11]
 [ 2 20  1  8  1]
 [ 4 11  1 10  6]
 [16 16  1  7  6]]


In [38]:
# Ans 1.2
num2 = np.random.randint(1,17,size=(4,4))
print(f"original array:\n{num2}")
np.fill_diagonal(num2,0)
print(f"\nmodified array:\n{num2}")

original array:
[[ 9  9  2  2]
 [12  3  9  2]
 [13  7 14  9]
 [ 6  8  1  2]]

modified array:
[[ 0  9  2  2]
 [12  0  9  2]
 [13  7  0  9]
 [ 6  8  1  0]]


In [48]:
# Ans 2.1
num3 = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(f"original array:\n{num3}")
print(f"\nextracted array from 3rd to 5th row and 2nd to 4th column:\n{num3[2:5,1:4]}")

Original array:
original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

extracted array from 3rd to 5th row and 2nd to 4th column:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [66]:
# Ans 2.2
num4 = np.random.randint(100,size=(5,5))
print(f"original array:\n{num4}")
print(f"\n border elements:\n{np.concatenate((num4[0, :], num4[4, :], num4[1:4, 0], num4[1:4, 4]))}")

original array:
[[61 49 13 48 58]
 [98 61 74 85 52]
 [54 15 21 13  1]
 [ 3 74 17  3 16]
 [35 77 41 64 99]]

 border elements:
[61 49 13 48 58 35 77 41 64 99 98 54  3 52  1 16]


In [68]:
# Ans 3.1
num5 = np.random.randint(100,size=(3,4))
num6 = np.random.randint(100,size=(3,4))
print(f"original array 1:\n{num5}")
print(f"original array 2:\n{num6}")
print(f"element wise addition:\n{np.add(num5,num6)}")
print(f"element wise subtraction:\n{np.subtract(num5,num6)}")
print(f"element wise multiplication:\n{np.multiply(num5,num6)}")
print(f"element wise division:\n{np.divide(num5,num6)}")

original array 1:
[[41  7 56 56]
 [95 77 32 34]
 [21  9 86 83]]
original array 2:
[[26 60 61 63]
 [22 67 42 90]
 [66 72 52  8]]
element wise addition:
[[ 67  67 117 119]
 [117 144  74 124]
 [ 87  81 138  91]]
element wise subtraction:
[[ 15 -53  -5  -7]
 [ 73  10 -10 -56]
 [-45 -63  34  75]]
element wise multiplication:
[[1066  420 3416 3528]
 [2090 5159 1344 3060]
 [1386  648 4472  664]]
element wise division:
[[ 1.57692308  0.11666667  0.91803279  0.88888889]
 [ 4.31818182  1.14925373  0.76190476  0.37777778]
 [ 0.31818182  0.125       1.65384615 10.375     ]]


In [75]:
# Ans 3.2
num7 = np.arange(1,17).reshape((4,4))
print(f"original array:\n{num7}")
print(f"\nrow wise sum:\n{np.sum(num7, axis=1)}")
print(f"\ncolumn wise sum:\n{np.sum(num7, axis=0)}")

original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

row wise sum:
[10 26 42 58]

column wise sum:
[28 32 36 40]


In [78]:
# Ans 4.1
num8 = np.random.randint(1, 21, size=(5, 5))
print(f"Original array:{num8}")
print(f"Mean:,{np.mean(num8)}")
print(f"Median:,{np.median(num8)}")
print(f"Standard Deviation:,{np.std(num8)}")
print(f"Variance:{np.var(num8)}")

Original array:[[19  4  8 18 11]
 [ 5  2 12 12  8]
 [14 10  6  6 12]
 [ 2  3 20 20  6]
 [16 18  1 12 15]]
Mean:,10.4
Median:,11.0
Standard Deviation:,5.912698199637792
Variance:34.959999999999994


In [ ]:
# Ans 4.2
num9 = np.arange(1, 10).reshape((3, 3))
print(f"Original array:{num9}")
mean = np.mean(num9)
std_dev = np.std(num9)
normalized_array = (num9 - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [97]:
# Ans 5.1
num10 = np.random.randint(100, size=(3,3))
num11 = np.array([10,11,12])
print(f"original array:\n{num10}")
print(f"array to be added:\n{num11}")
print(f"array after adding:\n{num10 + num11}")

original array:
[[18 50 92]
 [92 96 32]
 [84  0 78]]
array to be added:
[10 11 12]
array after adding:
[[ 28  61 104]
 [102 107  44]
 [ 94  11  90]]


In [98]:
# Ans 5.2
num12 = np.random.randint(100, size=(4,4))
num13 = np.array([5,6,7,8])
print(f"original array:\n{num12}")
print(f"array to be subtracted:\n{num13}")
print(f"array after subtracting:\n{num12 - num13[:, np.newaxis]}")

original array:
[[45 75  2 15]
 [42 38 40 45]
 [38 71 29 29]
 [48 30  4 11]]
array to be subtracted:
[5 6 7 8]
array after subtracting:
[[40 70 -3 10]
 [36 32 34 39]
 [31 64 22 22]
 [40 22 -4  3]]


In [99]:
# Ans 6.1
num14 = np.random.randint(1, 11, size=(3, 3))
print(f"original matrix:\n{num14}")
print("determinant:\n",{np.linalg.det(num14)})
print(f"inverse:\n{np.linalg.det(num14)}")
print(f"eigenvalues:\n{np.linalg.eigvals(num14)}")

original matrix:
[[ 7  9 10]
 [ 1  3  2]
 [ 5  3  4]]
determinant:
 {-23.999999999999982}
inverse:
-23.999999999999982
eigenvalues:
[14.16278001 -1.38569323  1.22291322]


In [100]:
# Ans 6.2
# Create two NumPy arrays of shape (2, 3) and (3, 2)
num15 = np.random.randint(1, 11, size=(2, 3))
num16 = np.random.randint(1, 11, size=(3, 2))
print(f"array 1:\n{num15}")
print(f"array 2:\n{num16}")
print(f"matrix multiplication result:\n{np.dot(num15,num16)}")

array 1:
[[ 2  4  8]
 [ 2 10  1]]
array 2:
[[ 7  8]
 [ 7  8]
 [10  1]]
matrix multiplication result:
[[122  56]
 [ 94  97]]


In [103]:
# Ans 7.1
# Create a NumPy array of shape (3, 3) with values from 1 to 9
num17 = np.arange(1, 10).reshape((3, 3))
print(f"original array:{num17}")
reshaped_array_1 =num17.reshape((1, 9))
print(f"Reshaped array (1, 9):{num17.reshape((1, 9))}")
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print(f"Reshaped array (9, 1):{reshaped_array_2}")

original array:[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [104]:
# Ans 7.2
num18 = np.random.randint(1, 21, size=(5, 5))
print(f"Original array:{num18}")
flattened_array = num18.flatten()
print(f"Flattened array:{flattened_array}")
reshaped_array = flattened_array.reshape((5, 5))
print(f"Reshaped array:{reshaped_array}")


Original array:[[ 3 10  4 17  5]
 [ 6 11 18  6  6]
 [13 19 13 16 13]
 [16  6 12 18  1]
 [18  4 14 16 15]]
Flattened array:[ 3 10  4 17  5  6 11 18  6  6 13 19 13 16 13 16  6 12 18  1 18  4 14 16
 15]
Reshaped array:[[ 3 10  4 17  5]
 [ 6 11 18  6  6]
 [13 19 13 16 13]
 [16  6 12 18  1]
 [18  4 14 16 15]]


In [ ]:
# Ans 8.1
num19 = np.random.randint(1, 21, size=(5, 5))
print(f"Original array:{num19}")
corners = num19[[0, 0, -1, -1], [0, -1, 0, -1]]
print(f"Corner elements:{corners}")

Original array:[[15 11 10 13 18]
 [ 1 11 12 11  1]
 [14 15 13 19 15]
 [13 11 18 16  3]
 [ 6 20  3 13 14]]
Corner elements:[15 18  6 14]


In [108]:
# Ans 8.2
num20 = np.random.randint(1, 21, size=(4, 4))
print(f"Original array:{num20}")
num20[num20 > 10] = 10
print(f"Modified array:{num20}")


Original array:[[19 20 18 15]
 [ 1 13 19  3]
 [ 8  5 11 18]
 [ 3  1 11 11]]
Modified array:[[10 10 10 10]
 [ 1 10 10  3]
 [ 8  5 10 10]
 [ 3  1 10 10]]


In [ ]:
# Ans 9.1
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
num20 = np.array([('abhishek', 22, 62.7), ('atharva', 21, 65), ('harsh', 21, 65.2)], dtype=data_type)
print(f"Original array:{num21}")
sorted_data = np.sort(num20, order='age')
print(f"Sorted array by age:{sorted_data}")


Original array:[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
Sorted array by age:[('atharva', 21, 65. ) ('harsh', 21, 65.2) ('abhishek', 22, 62.7)]


In [114]:
# Ans 9.2
data_type = [('x', 'i4'), ('y', 'i4')]
num21 = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print(f"Original array:{num21}")
distances = np.sqrt((num21['x'][:, np.newaxis] - num21['x'])**2 + (num21['y'][:, np.newaxis] - num21['y'])**2)
print(f"Euclidean distances:{distances}")


Original array:[(1, 2) (3, 4) (5, 6)]
Euclidean distances:[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [ ]:
# Ans 10.1
import numpy.ma as ma

num22 = np.random.randint(1, 21, size=(4, 4))
masked_num1 = ma.masked_greater(num22, 10)
print(f"Original array:{num22}")
print(f"Masked array:{masked_num1}")
sum_unmasked = masked_num1.sum()
print(f"Sum of unmasked elements:{sum_unmasked}")

Original array:[[14  6 14 19]
 [ 9 12 16 12]
 [ 7 20  2  6]
 [10 10 10  5]]
Masked array:[[-- 6 -- --]
 [9 -- -- --]
 [7 -- 2 6]
 [10 10 10 5]]
Sum of unmasked elements:65


In [120]:
# Ans 10.2
num23 = np.random.randint(1, 21, size=(3, 3))
masked_num2 = ma.masked_array(num23, mask=np.eye(3, dtype=bool))
print(f"Original array:{num23}")
print(f"Masked array:{masked_num2}")
mean_unmasked = masked_num2.mean()
masked_array = masked_num2.filled(mean_unmasked)
print("Modified masked array:{masked_array}")
print(masked_array)

Original array:[[12 19  1]
 [10  9 10]
 [ 4 17  7]]
Masked array:[[-- 19 1]
 [10 -- 10]
 [4 17 --]]
Modified masked array:{masked_array}
[[10 19  1]
 [10 10 10]
 [ 4 17 10]]
