# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.


In [1]:
# Ans 1.1
import pandas as pd
import numpy as np
import random
df1 = pd.DataFrame(np.random.randint(100,size=(6,4)), columns = list('ABCD'))
print(f"original DataFrame:\n{df1}")
df1.set_index('A', inplace = True)
print(f"dataframe with index at first column:\n{df1}")

original DataFrame:
    A   B   C   D
0   3  67  77  21
1  53  95  65  78
2  56  30  21  34
3  63  91  42   3
4   5  60  74  86
5  15  30  82  61
dataframe with index at first column:
     B   C   D
A             
3   67  77  21
53  95  65  78
56  30  21  34
63  91  42   3
5   60  74  86
15  30  82  61


In [9]:
# Ans 1.2
df2 = pd.DataFrame(np.random.randint(100,size = (3,3)),columns = list('ABC'), index = ('X','Y','Z'))
print(f"dataframe with modified index:\n{df2}")
print("elemnet at row index 'Y' and column index 'B':", df2.loc['Y', 'B'])

dataframe with modified index:
    A   B   C
X  44   5  65
Y  48  10  42
Z  85  23  51
elemnet at row index 'Y' and column index 'B': 10


In [ ]:
# Ans 2.1
df3 = pd.DataFrame(np.random.randint(100, size=(5,3)))
print(f"original dataframe:\n{df3}")
df3[3] = df3[0] * df3[1]
print(f"new dataframe:\n{df3}")

original dataframe:
    0   1   2
0  44  86   4
1  80   5  27
2  37  51  59
3  20  10  34
4  23  17  41
new dataframe:
    0   1   2     3
0  44  86   4  3784
1  80   5  27   400
2  37  51  59  1887
3  20  10  34   200
4  23  17  41   391


In [23]:
# Ans 2.2
df4 = np.random.randint(100,size = (4,3))
print(f"original dataframe:\n{df4}\n")
print(f"row wise sum:{df4.sum(axis = 0)}\n")
print(f"columan wise sum:{df4.sum(axis=1)}")

original dataframe:
[[13 17 88]
 [11 45 69]
 [40 74  8]
 [25 76 76]]

row wise sum:[ 89 212 241]

columan wise sum:[118 125 122 177]


In [39]:
# Ansd 3.1
df5 = pd.DataFrame(np.random.randint(100,size = (6,4)), columns = list('ABCD'))
print(f"original dataframe:\n{df5}")
df5.iloc[0,1] = np.nan
df5.iloc[1,2] = np.nan
df5.iloc[4,3] = np.nan
print(f"dataframe with NaN values:\n{df5}")
df5.fillna(df5.mean(),inplace=True)
print(f"dataframe with NaN values replaced by mean of their respective columns:\n{df5}")

original dataframe:
    A   B   C   D
0  81  48  38  56
1  94  88  28   2
2  71  53  99  47
3  99   1  27   8
4   3  35  91  34
5  93  45  70  34
dataframe with NaN values:
    A     B     C     D
0  81   NaN  38.0  56.0
1  94  88.0   NaN   2.0
2  71  53.0  99.0  47.0
3  99   1.0  27.0   8.0
4   3  35.0  91.0   NaN
5  93  45.0  70.0  34.0
dataframe with NaN values replaced by mean of their respective columns:
    A     B     C     D
0  81  44.4  38.0  56.0
1  94  88.0  65.0   2.0
2  71  53.0  99.0  47.0
3  99   1.0  27.0   8.0
4   3  35.0  91.0  29.4
5  93  45.0  70.0  34.0


In [41]:
# Ans 3.2
df6 = pd.DataFrame(np.random.randint(100,size = (6,4)), columns = list('ABCD'))
print(f"original dataframe:\n{df5}")
df6.iloc[0,1] = np.nan
df6.iloc[1,2] = np.nan
df6.iloc[4,3] = np.nan
print(f"dataframe with NaN values:\n{df6}")
print(f"datframe with dropped rows which contain NaN values:\n{df6.dropna()}")

original dataframe:
    A     B     C     D
0  81  44.4  38.0  56.0
1  94  88.0  65.0   2.0
2  71  53.0  99.0  47.0
3  99   1.0  27.0   8.0
4   3  35.0  91.0  29.4
5  93  45.0  70.0  34.0
dataframe with NaN values:
    A     B     C     D
0   5   NaN  46.0  31.0
1   2  95.0   NaN  96.0
2  86  77.0  41.0   8.0
3  65  57.0  58.0  15.0
4  45  49.0  81.0   NaN
5  63  34.0  40.0  23.0
datframe with dropped rows which contain NaN values:
    A     B     C     D
2  86  77.0  41.0   8.0
3  65  57.0  58.0  15.0
5  63  34.0  40.0  23.0


In [48]:
# Ans 4.1
df7 = pd.DataFrame({ 'Category' : np.random.choice(['A','B','C'],size=10), 'Value' : [np.random.randint(100) for _ in range(10)]})
print(f"original dataframe:\n{df7}")
print(df7.groupby('Category').agg(['sum','mean']))

original dataframe:
  Category  Value
0        B      9
1        A     70
2        B     20
3        A     87
4        B     58
5        A     10
6        B     83
7        A     46
8        C     16
9        A     31
         Value      
           sum  mean
Category            
A          244  48.8
B          170  42.5
C           16  16.0


In [56]:
# Ans 4.2
df8 = pd.DataFrame({'Category' : np.random.choice(['A','B','C'], size=10), 'Value' : np.random.randint(100,size=10), 'Sales' : np.random.randint(1000, size=10)})
print(f"original dataframe:\n{df8}")
print("\ntotal sales by each category:")
df8.groupby('Category')['Sales'].sum()

original dataframe:
  Category  Value  Sales
0        C     75    951
1        B     18    101
2        A     34    252
3        B     60    347
4        A     87    775
5        A     31    101
6        C     22    103
7        A     28    388
8        C     23    485
9        A     15    265

total sales by each category:


Category
A    1781
B     448
C    1539
Name: Sales, dtype: int32

In [59]:
# Ans 5.1
df9 = pd.DataFrame({'Name' : ['abhishek','harsh','atharva','pratham','sachin'], 'Phone' : [45515,55451,98753,32154,48748], 'id_no' : [1,2,3,4,5]})
print(f"original dataframe number 1:\n{df9}")
df10 = pd.DataFrame({'Name' : ['abhishek','harsh','atharva','pratham','sachin'], 'mail' : ['abcd','efgh','ijkl','mnop','qrst'], 'salary':[10000,20000,30000,40000,50000]})
print(f"original dataframe number 2:\n{df10}")
df11 = pd.merge(df9,df10, on = 'Name', how = 'inner')
print(f"merged dataframe:\n{df11}")

original dataframe number 1:
       Name  Phone  id_no
0  abhishek  45515      1
1     harsh  55451      2
2   atharva  98753      3
3   pratham  32154      4
4    sachin  48748      5
original dataframe number 2:
       Name  mail  salary
0  abhishek  abcd   10000
1     harsh  efgh   20000
2   atharva  ijkl   30000
3   pratham  mnop   40000
4    sachin  qrst   50000
merged dataframe:
       Name  Phone  id_no  mail  salary
0  abhishek  45515      1  abcd   10000
1     harsh  55451      2  efgh   20000
2   atharva  98753      3  ijkl   30000
3   pratham  32154      4  mnop   40000
4    sachin  48748      5  qrst   50000


In [63]:
# Ans 5.2
df12 = pd.DataFrame({'Name' : ['abhishek','harsh','atharva','pratham','sachin'], 'Phone' : [45515,55451,98753,32154,48748], 'id_no' : [1,2,3,4,5]})
print(f"original dataframe number 1:\n{df12}")
df13 = pd.DataFrame({'mail' : ['abcd','efgh','ijkl','mnop','qrst'], 'salary':[10000,20000,30000,40000,50000]})
print(f"original dataframe number 2:\n{df13}")
df14 = pd.concat([df12, df13],axis=1)
print(f"concatenated dataframe:\n{df14}")

original dataframe number 1:
       Name  Phone  id_no
0  abhishek  45515      1
1     harsh  55451      2
2   atharva  98753      3
3   pratham  32154      4
4    sachin  48748      5
original dataframe number 2:
   mail  salary
0  abcd   10000
1  efgh   20000
2  ijkl   30000
3  mnop   40000
4  qrst   50000
concatenated dataframe:
       Name  Phone  id_no  mail  salary
0  abhishek  45515      1  abcd   10000
1     harsh  55451      2  efgh   20000
2   atharva  98753      3  ijkl   30000
3   pratham  32154      4  mnop   40000
4    sachin  48748      5  qrst   50000


In [84]:
# Ans 6.1
date_rng = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
df15 = pd.DataFrame({'date' : date_rng, 'data':  np.random.randint(0, 100, size=(len(date_rng)))})
df15.set_index('date', inplace=True)
print(f"Original DataFrame:\n{df}")
monthly_mean = df.resample('ME').mean()
print(f"Monthly mean DataFrame:\n{monthly_mean}")

Original DataFrame:
            data
date            
2022-01-01    37
2022-01-02    89
2022-01-03    95
2022-01-04    34
2022-01-05    67
...          ...
2022-12-27    65
2022-12-28    26
2022-12-29    80
2022-12-30    37
2022-12-31    42

[365 rows x 1 columns]
Monthly mean DataFrame:
                 data
date                 
2022-01-31  47.322581
2022-02-28  55.142857
2022-03-31  44.387097
2022-04-30  51.833333
2022-05-31  45.032258
2022-06-30  52.433333
2022-07-31  55.806452
2022-08-31  50.612903
2022-09-30  52.266667
2022-10-31  49.709677
2022-11-30  54.466667
2022-12-31  49.419355


In [ ]:
# Ans 6.2
date_rng = pd.date_range(start='2021-01-01', end='2021-12-31', freq='D')
df16 = pd.DataFrame({'date' : date_rng, 'data' : np.random.randint(100,size=(len(date_rng)))})
df16.set_index('date', inplace=True)
print(f"original datframe:\n{df16}")
df17 = df16.rolling(window=7).mean()
print(f"dataframe with rolling mean of window = 7:\n{df17}")

original datframe:
            data
date            
2021-01-01     6
2021-01-02     9
2021-01-03    76
2021-01-04    54
2021-01-05    51
...          ...
2021-12-27    34
2021-12-28    70
2021-12-29    22
2021-12-30    39
2021-12-31    76

[365 rows x 1 columns]
dataframe with rolling mean of window = 7:
                 data
date                 
2021-01-01        NaN
2021-01-02        NaN
2021-01-03        NaN
2021-01-04        NaN
2021-01-05        NaN
...               ...
2021-12-27  59.000000
2021-12-28  62.142857
2021-12-29  55.714286
2021-12-30  49.285714
2021-12-31  49.285714

[365 rows x 1 columns]


In [91]:
# Ans 7.1
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df18 = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print(f"MultiIndex DataFrame:\n{df18}")
print(f"Indexing at Category 'A':\n{df18.loc['A']}")
print(f"Slicing at Category 'B' and SubCategory 'two':\n{df18.loc[('B', 'two')]}")

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory                        
A        one              96      63      33
         two              53      40      68
B        one              93      76      38
         two               7      84      67
Indexing at Category 'A':
             Value1  Value2  Value3
SubCategory                        
one              96      63      33
two              53      40      68
Slicing at Category 'B' and SubCategory 'two':
Value1     7
Value2    84
Value3    67
Name: (B, two), dtype: int32


In [92]:
# Ans 7.2
arrays = [['A', 'A', 'B', 'B', 'C', 'C'], ['one', 'two', 'one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df19 = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print(f"MultiIndex DataFrame:\n{df19}")

# Compute the sum of values for each 'Category' and 'SubCategory'
sum_values = df19.groupby(['Category', 'SubCategory']).sum()
print(f"Sum of values:\n{sum_values}")

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory                        
A        one              42      28      79
         two              17      72      71
B        one              15      11      38
         two              78      90      33
C        one              65      58      57
         two              73       4      35
Sum of values:
                      Value1  Value2  Value3
Category SubCategory                        
A        one              42      28      79
         two              17      72      71
B        one              15      11      38
         two              78      90      33
C        one              65      58      57
         two              73       4      35


In [93]:
# Ans 8.1
date_rng = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df20 = pd.DataFrame({'Date': np.random.choice(date_rng, size=20), 'Category': np.random.choice(['A', 'B', 'C'], size=20), 'Value': np.random.randint(1, 100, size=20)})
print(f"Original DataFrame:\n{df20}")
pivot_table = df20.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum')
print(f"Pivot Table:\n{pivot_table}")

Original DataFrame:
         Date Category  Value
0  2022-01-09        C     16
1  2022-01-09        B     37
2  2022-01-09        B     74
3  2022-01-08        B     13
4  2022-01-01        C     96
5  2022-01-03        C     20
6  2022-01-04        B     20
7  2022-01-09        A     68
8  2022-01-01        B      6
9  2022-01-09        B     26
10 2022-01-07        A     43
11 2022-01-03        A     91
12 2022-01-03        B     13
13 2022-01-02        C      1
14 2022-01-01        C     76
15 2022-01-01        C     47
16 2022-01-07        B     36
17 2022-01-07        C     90
18 2022-01-10        A     98
19 2022-01-07        A      7
Pivot Table:
Category       A      B      C
Date                          
2022-01-01   NaN    6.0  219.0
2022-01-02   NaN    NaN    1.0
2022-01-03  91.0   13.0   20.0
2022-01-04   NaN   20.0    NaN
2022-01-07  50.0   36.0   90.0
2022-01-08   NaN   13.0    NaN
2022-01-09  68.0  137.0   16.0
2022-01-10  98.0    NaN    NaN


In [94]:
# Ans 8.2
df21 = pd.DataFrame({'Year': np.random.choice([2023, 2024, 2025], size=12), 'Quarter': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=12), 'Revenue': np.random.randint(1, 1000, size=12)})
print(f"Original DataFrame:\n{df21}")
pivot_table = df21.pivot_table(values='Revenue', index='Year', columns='Quarter', aggfunc='mean')
print(f"Pivot Table:\n{df21}")

Original DataFrame:
    Year Quarter  Revenue
0   2023      Q4      817
1   2023      Q1      141
2   2024      Q2      718
3   2024      Q4      714
4   2024      Q4      453
5   2023      Q3      539
6   2024      Q1        6
7   2024      Q4      766
8   2023      Q2      606
9   2024      Q4      912
10  2025      Q4       93
11  2023      Q2      665
Pivot Table:
    Year Quarter  Revenue
0   2023      Q4      817
1   2023      Q1      141
2   2024      Q2      718
3   2024      Q4      714
4   2024      Q4      453
5   2023      Q3      539
6   2024      Q1        6
7   2024      Q4      766
8   2023      Q2      606
9   2024      Q4      912
10  2025      Q4       93
11  2023      Q2      665


In [97]:
# Ans 9.1
df22 = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:\n{df22}")
df_doubled = df22.map(lambda x: x * 2)
print(f"Doubled DataFrame:\n{df_doubled}")

Original DataFrame:
{df22}
Doubled DataFrame:
     A    B   C
0  174  142   8
1  188  172  84
2  188    8  38
3   48   24  22
4   86   32  88


In [ ]:
# Ans 9.2
df23 = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), columns=['A', 'B', 'C'])
print(f"Original DataFrame:\n{df23}")
df23['Sum'] = df.apply(lambda row: row.sum(), axis=1)
print(f"DataFrame with Sum column:\n{df23}")

Original DataFrame:
    A   B   C
0  39  16  36
1  70  26  20
2  13  86   6
3  21  72  34
4  69  92  18
5  69  43   8
DataFrame with Sum column:
    A   B   C  Sum
0  39  16  36  NaN
1  70  26  20  NaN
2  13  86   6  NaN
3  21  72  34  NaN
4  69  92  18  NaN
5  69  43   8  NaN


In [101]:
# Ans 10.1
text_data = pd.Series(['apple', 'banana', 'mango', 'guava', 'jamun'])
print(f"Original Series:\n{text_data}")
uppercase_data = text_data.str.upper()
print(f"Uppercase Series:\n{uppercase_data}")

Original Series:
0     apple
1    banana
2     mango
3     guava
4     jamun
dtype: object
Uppercase Series:
0     APPLE
1    BANANA
2     MANGO
3     GUAVA
4     JAMUN
dtype: object


In [102]:
# Ans 10.2
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print(f"Original Series:\n{text_data}")
first_three_chars = text_data.str[:3]
print(f"First three characters:\n{first_three_chars}")

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object
First three characters:
0    app
1    ban
2    che
3    dat
4    eld
dtype: object
